### ISSUE TITLE
Could not build on vercel or netlify

### ISSUE THREAD

**Issue by maziano** [btahir/next-shopify-starter#2]

**Comment by maziano** [comment]
Hi thanks for the template but I could not successfully deploy the site template on netlify or vercel. Please comment and respond. Thank you for the help.

**Comment by btahir** [comment]
What do you want me to say? Look at the errors - figure it out.

**Comment by maziano** [comment]
Wow! Such an awesome comment.

**Comment by maziano** [comment]
😁
