### ISSUE TITLE
Error when adding a product to cart after already completing checkout

### ISSUE THREAD

**Issue by olijones** [btahir/next-shopify-starter#5]
Hi there, thank you for sharing your Next + Shopify starter! 

I've noticed one wee issue in which if you complete an order using the Shopify checkout and then return to the site, the cart persists. 

This then allows you to add another product to the cart which throws an error as the cart has already been completed from Shopify's perspective. Would it be possible to clear the cart after the checkout has been successfully completed?

If you have time to amend this that would be great, otherwise I'll have a look when I get a chance to use the starter.

Thanks again for sharing!

**Comment by btahir** [comment]
Currently the Checkout Button is[ just a link](https://github.com/btahir/next-shopify-starter/blob/main/components/CheckOutButton.js) that takes you to Shopify Checkout. You can convert this into a button and send the user to Shopify checkout (using next/router) as well as clear the cart in an onClick function.

You can create a clearCart function in the Context Store that simply sets the cart state back to an empty array.

I probably won't have time to implement this and test it out for now but hopefully this helps.

**Comment by MrUltimate** [comment]
Hi @olijones!

Were you ever able to figure this out? Clearing the cart on checkout seems like a bad idea because a lot of customers tend to bail at the hosted checkout page after seeing the total price. Ideally I'd like to only clear the cart when they successfully place an order.
